### ISSUE TITLE
Show how to get data out of the AccessToken in NativeFacebookLogin

### ISSUE THREAD

**Issue by ollef** [fusetools/fuse-samples#35]
Several users have asked for this.

**Comment by jesusmartinoza** [comment]
I made the code for android but can't find the **NativeFacebookLogin** project :/

**Comment by jesusmartinoza** [comment]
Here is the code for android 
https://github.com/Betobit/fuse-samples/tree/master/Samples/NativeFacebookLogin

When I finish the iOS version I do a pull request :)

**Comment by ollef** [comment]
Wow, nice work!

The original code is on the `feature-NativeFacebookLogin` branch, so make the PR against that. It'll be merged to master eventually, but is on a branch for internal reasons (specifically because it uses Gradle, which requires a non-standard Uno flag which messes with our internal testing).

**Comment by jesusmartinoza** [comment]
Oh I missed that! A PR will be done, thank you.

**Comment by jmoleiro** [comment]
Hi! 

I tried the sample project for Native Facebook Login (https://github.com/fusetools/fuse-samples/tree/feature-NativeFacebookLogin/Samples/NativeFacebookLogin) and it seems to compile without warning, but when i tried it on an Android device, i get this exception

```
Uno.Exception: The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.
   at Android.Base.JNI.TryGetException(Android.Base.Primitives.JNIEnvPtr,[string])
   at Android.Base.JNI.CheckException(Android.Base.Primitives.JNIEnvPtr,[string])
   at Android.Base.JNI.CheckException(Android.Base.Primitives.JNIEnvPtr)
   at FacebookLoginModule.FacebookLoginPromise.Login()
   at Fuse.UpdateListener.Invoke()
   at Fuse.UpdateManager.ProcessOnces(Fuse.Stage,Uno.Collections.List<Uno.Exception>&)
   at Fuse.UpdateManager.Update(Fuse.Stage)
   at Fuse.UpdateManager.ProcessStages()
   at Fuse.UpdateManager.Update()
   at Outracks.Simulator.Client.Application.OnUpdate()
   at Fuse.App.OnTick(object,Uno.Platform.TimerEventArgs)
   at Uno.Platform.Display.OnTick(Uno.Platform.TimerEventArgs)
   at Uno.Platform.AndroidDisplay.OnFrameCallback(double,double)
```
I get this error with the sample project. Tried on a new project i get the same error. 

On iOS it works ok. Any ideas?

**Comment by jesusmartinoza** [comment]
Hi! That's the official repo. Try with my fork and tell me how it works :)

Here is the link:
https://github.com/jesusmartinoza/fuse-samples

Regards!
